import type {MachinePlan, Purchase} from "./api";
import {useEffect,useRef,useState, type FormEvent} from 'react';
import {ArrowUpRight,ArrowDownLeft,ArrowRight,ArrowUp,Wallet as WalletIcon,Sparkles,Clock3,Settings2,ShieldCheck,Check,Copy,X,ChevronRight,WifiOff,LoaderCircle,Plus,CheckCircle2,ExternalLink} from 'lucide-react';
import {api,ApiError,approvePlan,units,short,type Wallet,type Session,type Plan,type Activity,type Asset} from './api';
type Tab='Home'|'Agent'|'Activity'|'Settings';
const tabs=[{name:'Home' as Tab,icon:WalletIcon},{name:'Agent' as Tab,icon:Sparkles},{name:'Activity' as Tab,icon:Clock3},{name:'Settings' as Tab,icon:Settings2}];
export function StatusBadge({status}:{status:Activity['status']}){return <span className={`status ${status}`}><span/>{status[0].toUpperCase()+status.slice(1)}</span>}
export function ApprovalSheet({plan,asset,busy,onAction}:{plan:Plan;asset?:Asset;busy:boolean;onAction:(yes:boolean)=>void}) {
  const cancel=useRef<HTMLButtonElement>(null);useEffect(()=>{cancel.current?.focus()},[plan.plan_id]);
  return <div className="scrim"><section className="sheet" role="dialog" aria-modal="true" aria-labelledby="approval-title" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onAction(false);if(e.key==='Tab'){const nodes=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),summary');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}>
    <div className="sheet-handle"/><div className="sheet-icon"><ShieldCheck size={27}/></div><p className="eyebrow">YOUR APPROVAL, YOUR CONTROL</p><h2 id="approval-title">Confirm payment</h2>
    <div className="confirm-amount">{units(plan.request.amount,asset?.precision)} <span>{asset?.ticker??'RGB units'}</span></div><p className="muted">Demo RGB asset · One-time payment</p>
    <dl className="details"><div><dt>To</dt><dd>{plan.recipient?.identifier??'Invoice destination'}<br/><small>{plan.recipient?.authoritative_domain??short(plan.request.payment_hash)}</small></dd></div><div><dt>Network</dt><dd>RGB over Lightning</dd></div><div><dt>Carrier</dt><dd>{units(plan.request.carrier_msat,3)} sats<br/><small>+ node-managed routing fees</small></dd></div><div><dt>Available</dt><dd>{units(plan.available_balance,asset?.precision)} {asset?.ticker??'base units'}</dd></div><div><dt>Wallet policy</dt><dd>{plan.policy.decision==='require_approval'?'Manual approval required':plan.policy.decision==='deny'?'Denied':'Within wallet limits'}<br/><small>{plan.policy.reason}</small></dd></div></dl>
    <details className="invoice-details"><summary>{plan.recipient?'View exact payment & asset':'View exact invoice & asset'}</summary><p>Asset: {plan.request.asset_id}</p><p>Amount: {plan.request.amount} base units</p><p>{plan.request.invoice}</p><p>Plan: {plan.plan_id}</p></details>
    <div className="sheet-actions"><button ref={cancel} className="button secondary" disabled={busy} onClick={()=>onAction(false)}>Cancel</button><button className="button primary" disabled={busy} onClick={()=>onAction(true)}>{busy?<LoaderCircle className="spin" size={18}/>:<ShieldCheck size={18}/>} Approve payment</button></div><p className="footnote">Only this prepared payment can be authorized.</p>
  </section></div>
}
export function ActivityList({items,assets}:{items:Activity[];assets:Asset[]}){return <div className="activity-list">{items.length===0?<div className="empty"><Clock3/><h3>Your activity starts here</h3><p>Payments will appear here with their verified status.</p></div>:items.map(item=>{const asset=assets.find(a=>a.asset_id===item.asset_id);const machine=item.kind==='machine_purchase';const received=item.direction==='received';return <article className="activity-row" key={item.payment_hash}><div className="activity-icon">{machine?<Sparkles size={22}/>:received?<ArrowDownLeft size={22}/>:<ArrowUpRight size={22}/>}</div><div className="activity-info"><strong>{machine?'Machine service':`${received?'Received':'Sent'} ${asset?.ticker??'RGB asset'}`}</strong><span>{new Date(item.timestamp*1000).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · {short(item.payment_hash)}</span>{machine&&<span>{item.auto_approved?'Policy auto-approved':'Human approved'} · {item.resource?.split('/').pop()}</span>}</div><div className="activity-value"><strong>{received?'+':'−'}{units(item.amount,machine?0:asset?.precision)}{machine?' sats':''}</strong><StatusBadge status={item.status}/></div></article>})}</div>}
export function MachineApprovalSheet({plan,busy,onAction}:{plan:MachinePlan;busy:boolean;onAction:(yes:boolean)=>void}){
  const cancel=useRef<HTMLButtonElement>(null);useEffect(()=>{cancel.current?.focus()},[]);
  return <div className="scrim"><section className="sheet" role="dialog" aria-modal="true" aria-labelledby="machine-approval-title" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onAction(false);if(e.key==='Tab'){const nodes=e.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><div className="sheet-handle"/><div className="sheet-icon"><ShieldCheck size={27}/></div><p className="eyebrow">MACHINE SERVICE · BTC LIGHTNING</p><h2 id="machine-approval-title">Approve service purchase</h2><div className="confirm-amount">{plan.cost_sats} <small>sats</small></div><dl className="details"><div><dt>Resource</dt><dd className="resource-url">{plan.url}</dd></div><div><dt>Wallet policy</dt><dd>Manual approval required<br/><small>Automatic payments up to {plan.auto_approve_up_to_sats} sats</small></dd></div><div><dt>Available</dt><dd>{plan.available_sats} sats</dd></div><div><dt>Fees</dt><dd>Node-managed routing fees</dd></div></dl><p className="footnote">Your approval authorizes this exact stored plan. The agent cannot approve it.</p><div className="sheet-actions"><button ref={cancel} className="button secondary" disabled={busy} onClick={()=>onAction(false)}>Cancel</button><button className="button primary" disabled={busy} onClick={()=>onAction(true)}>Approve {plan.cost_sats} sats</button></div></section></div>
}
export function MachineReceipt({purchase:p}:{purchase:Purchase}) {return <section className="payment-receipt machine-receipt" aria-label="Machine purchase result"><div><Sparkles size={20}/><strong>Premium report</strong></div><dl className="details"><div><dt>Service cost</dt><dd>{p.cost_sats} sats</dd></div><div><dt>Wallet policy</dt><dd>{p.auto_approved?`Auto-approved (up to ${p.auto_approve_up_to_sats} sats)`:p.policy.decision==='deny'?`Denied: ${p.policy.reason}`:'Human approval required'}</dd></div><div><dt>Payment</dt><dd>{p.payment_status?<StatusBadge status={p.payment_status}/>: 'Not submitted'}</dd></div><div><dt>Resource</dt><dd>{p.resource_status==='purchased'?'Unlocked':p.resource_status.replaceAll('_',' ')}</dd></div></dl>{p.resource&&<div className="purchased-resource">{Object.entries(p.resource).map(([key,value])=><p key={key}><strong>{key.replaceAll('_',' ')}: </strong>{typeof value==='object'?JSON.stringify(value):String(value)}</p>)}</div>}{p.payment_hash&&<small>Payment {short(p.payment_hash)}</small>}</section>}
export function PaymentReceipt({item,asset}:{item:Activity;asset?:Asset}) {return <section className="payment-receipt" aria-label="Current payment status"><div><CheckCircle2 size={20}/><strong>Latest wallet status</strong><StatusBadge status={item.status}/></div><h3>{units(item.amount,asset?.precision)} {item.kind==='machine_purchase'?'sats':asset?.ticker??'RGB units'}</h3><p>{short(item.payment_hash)}</p><small>Verified with your Lightning node</small></section>}
export default function App(){
  const [tab,setTab]=useState<Tab>('Home'),[wallet,setWallet]=useState<Wallet|null>(null),[session,setSession]=useState<Session|null>(null),[activity,setActivity]=useState<Activity[]>([]),[error,setError]=useState(''),[draft,setDraft]=useState(''),[sending,setSending]=useState(false),[receive,setReceive]=useState(false),[receiveInvoice,setReceiveInvoice]=useState(''),[receiveAsset,setReceiveAsset]=useState(''),[receiveAmount,setReceiveAmount]=useState(''),[issuing,setIssuing]=useState(false),[copied,setCopied]=useState(false),[online,setOnline]=useState(navigator.onLine),[connected,setConnected]=useState(false);
  const end=useRef<HTMLDivElement>(null);const assets=wallet?.holdings.map(h=>h.asset)??[];const primary=wallet?.holdings[0];const busy=sending||session?.busy||false;const currentPayment=activity.find(item=>session?.events.some(e=>e.kind==='payment'&&e.text.includes(item.payment_hash)));
  useEffect(()=>{let stopped=false;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const s=await api<Session>('/session');if(stopped)return;setSession(s);setConnected(true);if(!s.busy){const w=await api<Wallet>('/wallet');if(!stopped)setWallet(w);const a=await api<Activity[]>('/activity');if(!stopped)setActivity(a)} }catch(e){if(!stopped&&!(e instanceof ApiError&&e.status===409)){setConnected(false);setError(e instanceof Error?e.message:'Wallet backend unavailable')}}finally{if(!stopped)timer=setTimeout(poll,1500)}}void poll();return()=>{stopped=true;clearTimeout(timer)}},[]);
  useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[]);
  useEffect(()=>{end.current?.scrollIntoView?.({behavior:'smooth'})},[session?.events.length,tab]);
  async function send(event?:FormEvent){event?.preventDefault();if(!draft.trim()||!session||busy||!online||!connected)return;setSending(true);setError('');try{await api('/agent/message',session.csrf,{message:draft.trim()});setDraft('');setSession({...session,busy:true});setTab('Agent')}catch(e){setError(e instanceof Error?e.message:'Message could not be sent')}finally{setSending(false)}}
  async function approval(yes:boolean){const plan=session?.machine_pending??session?.pending;if(!session||!plan||busy||!online||!connected)return;setSending(true);setError('');try{await approvePlan(plan.plan_id,session.csrf,yes);setSession({...session,pending:null,machine_pending:null,busy:true})}catch(e){setError(e instanceof Error?e.message:'Approval outcome unavailable. Check activity before retrying.')}finally{setSending(false)}}
  function ask(text=''){setDraft(text);setTab('Agent')}
  return <div className="app-frame"><aside className="desktop-rail"><Brand/><p>Your assets.<br/>Your decisions.</p><div className="rail-art"><span>R</span><span>G</span><span>B</span></div><div className="rail-note"><ShieldCheck size={20}/><span>Built on Bitcoin.<br/>Always in your control.</span></div></aside><div className="wallet-shell">
    <header className="topbar"><Brand/><div className="network-pill"><span/> REGTEST</div></header>
    {(!online||!connected)&&<div className="connection-note"><WifiOff size={15}/>{!online?'You’re offline. Payments are unavailable.':'Connecting to your local wallet…'}</div>}
    {error&&<div className="error-banner" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
    <main>
    {tab==='Home'&&<><div className="page-heading"><div><p className="eyebrow">{wallet?.wallet_name??'RGB Wallet'}</p><h1>A little more freedom.</h1></div><button className="round-button" aria-label="Wallet settings" onClick={()=>setTab('Settings')}><Settings2 size={19}/></button></div>
      <section className="balance-card"><div className="balance-top"><span>Lightning balance</span><div className="asset-mark">R</div></div><div className="balance-number" data-testid="primary-balance">{primary?units(primary.outbound,primary.asset.precision):'—'}</div><div className="balance-bottom"><span>{primary?.asset.ticker??'RGB assets'} <span className="demo-tag">Demo RGB asset</span></span><span className="lightning">ϟ</span></div><div className="card-line"/></section>
      <div className="quick-actions"><button onClick={()=>ask('Pay this RGB Lightning invoice: ')}><span><ArrowUpRight size={23}/></span>Send</button><button onClick={()=>setReceive(true)}><span><ArrowDownLeft size={23}/></span>Receive</button><button onClick={()=>ask()}><span className="orange"><Sparkles size={22}/></span>Ask agent</button></div>
      <section className="ask-card" onClick={()=>ask()}><div className="ask-icon"><Sparkles size={21}/></div><div><h3>A wallet that understands you.</h3><p>Ask a question. Make a payment.<br/>You’re always the one to approve.</p></div><button aria-label="Open Agent"><ArrowUpRight size={21}/></button></section>
      <div className="section-heading"><h2>Your assets</h2><span>{wallet?.holdings.length??'—'} assets</span></div><div className="assets-card">{wallet?.holdings.map(h=><div className="asset-row" key={h.asset.asset_id}><div className="coin">R</div><div><strong>{h.asset.ticker}</strong><small>RGB · Lightning</small></div><div className="asset-value"><strong>{units(h.outbound,h.asset.precision)}</strong><small>On-chain: {units(h.onchain,h.asset.precision)}</small></div></div>)}<div className="btc-note"><span className="bitcoin">₿</span><div><strong>Bitcoin</strong><small>Sats balance not available from this wallet</small></div><span>—</span></div></div>
      <div className="section-heading"><h2>Recent activity</h2><button onClick={()=>setTab('Activity')}>View all <ChevronRight size={14}/></button></div><ActivityList items={activity.slice(0,3)} assets={assets}/><div className="home-footer"><ShieldCheck size={14}/> Your approval is the final word.</div>
    </>}
    {tab==='Agent'&&<div className="agent-page"><div className="page-heading"><div><p className="eyebrow">A LITTLE HELP, ON YOUR TERMS</p><h1>Your wallet agent.</h1></div><div className="agent-avatar"><Sparkles size={22}/></div></div><div className="chat" aria-live="polite">{!session?.events.length&&<div className="chat-welcome"><div className="welcome-glyph"><Sparkles size={34}/></div><h2>What can I help with?</h2><p>Check your balance, understand an invoice,<br/>or prepare your next payment.</p><div className="suggestions">{['What’s in my wallet?','Get the premium report.'].map(t=><button key={t} onClick={()=>setDraft(t)}>{t}<ArrowUpRight size={17}/></button>)}</div></div>}{session?.events.map(e=><div key={e.id} className={`message ${e.kind}`}><div className="message-label">{e.kind==='user'?'You':e.kind==='assistant'?'Wallet agent':e.kind==='machine'?'Machine service':e.kind==='approval'?'Your decision':e.kind==='error'?'Wallet notice':'Wallet action'}</div><p>{e.text}</p></div>)}{busy&&<div className="thinking"><LoaderCircle size={16} className="spin"/>Working with your wallet…</div>}{session?.machine_result&&<MachineReceipt purchase={session.machine_result}/>} {currentPayment&&<PaymentReceipt item={currentPayment} asset={assets.find(a=>a.asset_id===currentPayment.asset_id)}/>}<div ref={end}/></div><form className="composer" onSubmit={send}><textarea aria-label="Message your wallet" placeholder="Ask anything, or paste an invoice…" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={16000} rows={2}/><button aria-label="Send message" disabled={busy||!draft.trim()||!online||!connected||!!session?.pending||!!session?.machine_pending}><ArrowUp size={21}/></button></form><p className="composer-note"><ShieldCheck size={12}/> Payments follow wallet policy. Required approvals stay with you.</p></div>}
    {tab==='Activity'&&<><div className="page-heading"><div><p className="eyebrow">EVERY MOVE, IN ONE PLACE</p><h1>Activity</h1></div><Clock3 size={25}/></div><div className="activity-intro"><span className="filter-chip">All payments</span><small>Verified with your node</small></div><ActivityList items={activity} assets={assets}/><p className="footnote">Pending and uncertain payments remain reserved. Status updates come from the RGB node.</p></>}
    {tab==='Settings'&&<><div className="page-heading"><div><p className="eyebrow">MADE FOR YOUR PEACE OF MIND</p><h1>Wallet settings</h1></div></div><section className="settings-card"><ShieldCheck/><h2>You stay in control.</h2><p>Every payment is checked by your wallet. Your approval authorizes only the exact payment you review.</p></section><dl className="details settings-details"><div><dt>Network</dt><dd>Bitcoin regtest</dd></div><div><dt>Assets</dt><dd>Demo RGB assets</dd></div><div><dt>Wallet session</dt><dd>{wallet?.wallet_name??'Local · Single wallet'}</dd></div><div><dt>Connection</dt><dd>{connected&&online?'Connected':'Unavailable'}</dd></div></dl><section className="install-card"><Plus size={22}/><h3>Make yourself at home.</h3><p>Install RGB Wallet from your browser’s menu. On iPhone, use Share → Add to Home Screen.</p></section><p className="footnote">Demo wallet only. R402USD is not official Tether USD₮. Offline payments are unavailable.</p></>}
    </main><nav className="bottom-nav" aria-label="Main navigation">{tabs.map(({name,icon:Icon})=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)} aria-current={tab===name?'page':undefined}><Icon size={21}/><span>{name}</span>{tab===name&&<i/>}</button>)}</nav>
    {session?.machine_pending&&<MachineApprovalSheet plan={session.machine_pending} busy={busy||!online||!connected} onAction={approval}/>}
    {session?.pending&&<ApprovalSheet plan={session.pending} asset={assets.find(a=>a.asset_id===session.pending?.request.asset_id)} busy={busy||!online||!connected} onAction={approval}/>}
    {receive&&<div className="scrim"><section className="sheet receive-sheet" role="dialog" aria-modal="true" aria-labelledby="receive-title"><button className="close-sheet" onClick={()=>setReceive(false)} aria-label="Close receive"><X/></button><div className="sheet-icon"><ArrowDownLeft/></div><h2 id="receive-title">Receive RGB</h2><p className="muted">Create an invoice for this wallet. Amounts are integer asset base units.</p><form onSubmit={async e=>{e.preventDefault();if(!session)return;setIssuing(true);setReceiveInvoice('');setError('');try{const result=await api<{invoice:string}>('/invoice',session.csrf,{asset_id:receiveAsset||assets[0]?.asset_id,amount:receiveAmount});setReceiveInvoice(result.invoice);setCopied(false)}catch(e){setError(e instanceof Error?e.message:'Invoice creation failed')}finally{setIssuing(false)}}}><label>Asset<select aria-label="Receiving asset" value={receiveAsset||assets[0]?.asset_id||''} onChange={e=>{setReceiveAsset(e.target.value);setReceiveInvoice('')}}>{assets.map(a=><option key={a.asset_id} value={a.asset_id}>{a.ticker}</option>)}</select></label><label>Amount (base units)<input aria-label="Receiving amount" inputMode="numeric" pattern="[0-9]+" value={receiveAmount} onChange={e=>{setReceiveAmount(e.target.value);setReceiveInvoice('')}} required/></label><p>Carrier: 3,000 sats · Expires in 1 hour</p><button className="button primary" disabled={issuing||!assets.length||!receiveAmount||busy||!session}>{issuing?'Creating…':'Create invoice'}</button></form><textarea aria-label="Receiving invoice" placeholder="Your generated invoice appears here" readOnly value={receiveInvoice} /><button className="button primary" disabled={!receiveInvoice.trim()} onClick={async()=>{try{await navigator.clipboard.writeText(receiveInvoice.trim());setCopied(true)}catch{setError('Copy unavailable. Select and copy the invoice manually.')}}}>{copied?<Check size={18}/>:<Copy size={18}/>} {copied?'Copied':'Copy invoice'}</button><p className="footnote">Only share an invoice you created for your own wallet.</p></section></div>}
  </div></div>
}
function Brand(){return <div className="brand"><span className="brand-icon"><span/><span/><span/></span><strong>rgb<span>wallet</span></strong></div>}
