import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import Merchant from './Merchant';
it('enables and edits a store with owner csrf and no payment or model call',async()=>{
 const store={profile:{enabled:false,public_catalog:false,display_name:"Bob's Store",merchant_id:'bob@example.com',accepted_assets:['rgb:test']},products:[],orders:[],status_refresh_failed:false};
 const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async(_,opts)=>new Response(JSON.stringify(opts?.method==='POST'?{...store,profile:{...store.profile,enabled:true,public_catalog:true}}:store)));
 render(<Merchant csrf="owner-session" assets={[{asset_id:'rgb:test',ticker:'TEST',name:'Test asset',precision:0}]}/>);
 await screen.findByLabelText('Enable merchant mode');
 expect(screen.queryByLabelText('Store name')).not.toBeInTheDocument();
 expect(screen.queryByRole('heading',{name:'Customer orders'})).not.toBeInTheDocument();
 fireEvent.click(screen.getByLabelText('Enable merchant mode'));
 expect(screen.getByLabelText('Store name')).toBeInTheDocument();
 fireEvent.click(screen.getByLabelText('Publish catalog'));
 fireEvent.click(screen.getByRole('button',{name:'Add product'}));
 fireEvent.change(screen.getByLabelText('Product ID'),{target:{value:'tea'}});
 fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Tea'}});
 fireEvent.change(screen.getByLabelText('Price (base units)'),{target:{value:'4'}});
 fireEvent.click(screen.getByRole('button',{name:'Save store'}));
 await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('Store saved'));
 const posts=fetch.mock.calls.filter(([,opts])=>opts?.method==='POST');
 expect(posts).toHaveLength(1);
 expect(screen.getByText(/No customer orders yet/)).toBeInTheDocument();
 fireEvent.click(screen.getByLabelText('Enable merchant mode'));
 expect(screen.queryByLabelText('Product ID')).not.toBeInTheDocument();
 expect(screen.getByRole('button',{name:'Save merchant mode'})).toBeInTheDocument();
 expect(posts[0][0]).toBe('/api/merchant');
 expect(posts[0][1]?.headers).toEqual({'Content-Type':'application/json','X-Wallet-CSRF':'owner-session'});
 expect(JSON.parse(posts[0][1]?.body as string)).toEqual({enabled:true,public_catalog:true,display_name:"Bob's Store",accepted_assets:['rgb:test'],products:[{id:'tea',name:'Tea',amount:'4',asset_id:'rgb:test',available:true}]});
});
