[package]
name = "rgb402-merchant"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
rgb402-core = { path = "../rgb402-core" }
rgb402-payment = { path = "../rgb402-payment" }
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

