[package]
name = "rgb402-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
rgb402-core = { path = "../rgb402-core" }
rgb402-payment = { path = "../rgb402-payment" }
serde.workspace = true
thiserror.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
axum.workspace = true
rgb402-merchant = { path = "../rgb402-merchant" }
tokio.workspace = true
tower.workspace = true
