[package]
name = "rgb402-agent"
version.workspace = true
edition.workspace = true
rust-version = "1.88"
license.workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
rgb402-core = { path = "../rgb402-core" }
rgb402-payment = { path = "../rgb402-payment" }
serde.workspace = true
thiserror.workspace = true
serde_json.workspace = true
tracing.workspace = true
tokio.workspace = true
sha2 = "0.10"
lightning-invoice = { git = "https://github.com/RGB-Tools/rust-lightning.git", rev = "e2a0b8e24dc919ccef289f103fd1f8e1974fcc1d", features = ["std"] }

[dev-dependencies]
bitcoin = "0.32.2"
axum.workspace = true
rgb402-merchant = { path = "../rgb402-merchant" }
tower.workspace = true
